apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  selector:
    matchLabels:
      component: zk
  serviceName: zk-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        component: zk
    spec:
      containers:
      - name: sasstify-zookeeper
        image: sasstify/sasstify.zookeeper:1.0-SNAPSHOT
        env:
          - name: SERVERS
            value: '1'
          - name: ZOO_TICK_TIME
            value: '2000'
          - name: ZOO_INIT_LIMIT
            value: '10'
          - name: ZOO_SYNC_LIMIT
            value: '5'
          - name: ZOO_HEAP
            value: '512M'
          - name: ZOO_MAX_CLIENT_CNXNS
            value: '60'
          - name: ZOO_SNAP_RETAIN_COUNT
            value: '3'
          - name: ZOO_PURGE_INTERVAL
            value: '12'
          - name: ZOO_MAX_SESSION_TIMEOUT
            value: '40000'
          - name: ZOO_MIN_SESSION_TIMEOUT
            value: '4000'
          - name: ZOO_LOG_LEVEL
            value: 'INFO'
          - name: ZOO_ENABLE_AUTH
            value: 'yes'
          - name: ZOO_SERVER_USERS
            value: 'sasstify'
          - name: ZOO_SERVER_PASSWORDS
            value: 'sasstify'
          - name: ZOO_CLIENT_USER
            value: 'sasstify'
          - name: ZOO_CLIENT_PASSWORD
            value: 'sasstify'
          #  TLS implementation is not done yet, it depends on centralizer artifact management component
        ports:
          - containerPort: 2181
            name: client
          - containerPort: 2888
            name: server
          - containerPort: 3888
            name: leader-election
        livenessProbe:
          exec:
            command:
              - /bin/bash
              - -c
              - /opt/sasstify/scripts/zookeeper/zookeeper-ready.sh
        volumeMounts:
        - name: datadir
          mountPath: /var/sasstify/zookeeper/
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi